export const GET_FORM_DATA_EMPLEO_BUSCADOR = "GET_FORM_EMPLEO_BUSCADOR";
export const GET_EMPLEOS_DISPONIBLES = "GET_EMPLEOS_DISPONIBLES";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
